name = "MobiusTransformations"
uuid = "4b09bada-36b4-4fc6-9b7c-f286cea146ee"
authors = ["LauBMo <laurea987@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
LinearAlgebra = "1.11.0"
UnPack = "1.0.2"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
